### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by rjhilgefort** [rjhilgefort/lodash-extras#8]
Add tests.

**Comment by njutte** [comment]
Test created for everything but Ember extras in following PRs
- #14
- #15 
- #16

**Comment by rjhilgefort** [comment]
@njutte Merged
- https://github.com/rjhilgefort/lodash-extras/commit/85555d8b46dc1595268e49780cd423e92e00d5ca
- https://github.com/rjhilgefort/lodash-extras/commit/36ab62ec1169456bcc7a80e0e8bb9cd89d847cc3
